# Dependencies
markdown:     rdiscount
#highlighter: pygments

# Permalinks
#permalink:    pretty

# Server
source:       ./docs
destination:  ./_site
exclude:      ['config', 'videos']
keep_files:   ['.git', '.svn', 'videos']

port:         9001
url:          http://localhost:9001
